FROM python:3.9-alpine

ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip



COPY ./requirements.txt .

RUN pip install -r requirements.txt

COPY . /code

WORKDIR /code



COPY ./entrypoint.sh .



ENTRYPOINT ["sh", "/code/entrypoint.sh"]


