# Generated by Django 5.0.3 on 2024-04-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(choices=[('category1', 'Category1'), ('category2', 'Category2'), ('category3', 'Category3'), ('pepper', 'Pepper'), ('dwarf_tomatoes', 'Dwarf tomatoes'), ('basilica', 'Basilica')], max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
