# Generated by Django 5.0.3 on 2024-04-22 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiwako',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eng_name', models.CharField(max_length=50)),
                ('Geo_name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wiwakebi_photos/')),
                ('wiwako', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='wiwako.wiwako')),
            ],
        ),
    ]
